<?php
use App\Models\{Guru,JadwalPelajaran,JamPelajaran,Kelas,Pengajaran,Semester};
use App\Services\{PeriodeAktif,ValidasiJadwal};
use Livewire\Attributes\Url;
use Livewire\Component;

new class extends Component {
    #[Url] public string $hari=''; #[Url] public string $semesterId=''; #[Url] public string $kelasId=''; #[Url] public string $guruId='';
    public bool $showForm=false; public ?int $editingId=null; public array $form=['pengajaran_id'=>'','hari'=>'senin','jam_pelajaran_id'=>''];
    public function mount():void{$this->semesterId=(string)(request('semesterId')?:app(PeriodeAktif::class)->semester()?->id);}
    public function openCreate():void{abort_unless(auth()->user()->can('jadwal.create'),403);$this->editingId=null;$this->form=['pengajaran_id'=>'','hari'=>'senin','jam_pelajaran_id'=>''];$this->showForm=true;}
    public function edit(int $id):void{abort_unless(auth()->user()->can('jadwal.update'),403);$j=JadwalPelajaran::findOrFail($id);$this->editingId=$id;$this->form=$j->only(['pengajaran_id','hari','jam_pelajaran_id']);$this->showForm=true;}
    public function save():void{abort_unless(auth()->user()->can($this->editingId?'jadwal.update':'jadwal.create'),403);$data=$this->validate(['form.pengajaran_id'=>'required|exists:pengajaran,id','form.hari'=>'required|in:senin,selasa,rabu,kamis,jumat,sabtu','form.jam_pelajaran_id'=>'required|exists:jam_pelajaran,id'])['form'];$p=Pengajaran::findOrFail($data['pengajaran_id']);app(ValidasiJadwal::class)->handle($p,$data['hari'],(int)$data['jam_pelajaran_id'],$this->editingId);JadwalPelajaran::updateOrCreate(['id'=>$this->editingId],$data);$this->showForm=false;session()->flash('success','Jadwal berhasil disimpan.');}
    public function delete(int $id):void{abort_unless(auth()->user()->can('jadwal.delete'),403);JadwalPelajaran::findOrFail($id)->delete();session()->flash('success','Jadwal berhasil dihapus.');}
    public function with():array{$u=auth()->user();$query=JadwalPelajaran::with(['pengajaran.semester.tahunAjaran','pengajaran.kelas','pengajaran.guru','pengajaran.mataPelajaran','jamPelajaran'])->when($this->semesterId,fn($q)=>$q->whereHas('pengajaran',fn($x)=>$x->where('semester_id',$this->semesterId)))->when($this->kelasId,fn($q)=>$q->whereHas('pengajaran',fn($x)=>$x->where('kelas_id',$this->kelasId)))->when($this->guruId,fn($q)=>$q->whereHas('pengajaran',fn($x)=>$x->where('guru_id',$this->guruId)))->when($this->hari,fn($q)=>$q->where('hari',$this->hari));if($u->hasRole('guru'))$query->whereHas('pengajaran',fn($q)=>$q->where('guru_id',$u->guru?->id));if($u->hasRole('siswa')){$kid=$u->siswa?->penempatanKelas()->where('status','aktif')->value('kelas_id');$query->whereHas('pengajaran',fn($q)=>$q->where('kelas_id',$kid));}return ['jadwal'=>$query->get()->sortBy(fn($x)=>array_search($x->hari,['senin','selasa','rabu','kamis','jumat','sabtu'])*100+$x->jamPelajaran->urutan),'semesters'=>Semester::with('tahunAjaran')->get(),'kelas'=>Kelas::orderBy('nama')->get(),'guru'=>Guru::orderBy('nama_lengkap')->get(),'pengajaran'=>Pengajaran::with(['semester.tahunAjaran','kelas','guru','mataPelajaran'])->where('status','aktif')->get(),'jam'=>JamPelajaran::where('jenis','pelajaran')->where('status','aktif')->orderBy('urutan')->get()];}
}; ?>
<div><div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-sky-700">Akademik</p><h1 class="page-title">Jadwal Pelajaran</h1><p class="page-subtitle">Jadwal mingguan sesuai kelas dan hak akses pengguna.</p></div>@can('jadwal.create')<button wire:click="openCreate" class="btn-primary">Tambah Jadwal</button>@endcan</div>
<form class="filters card mb-5 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-5"><select wire:model.live="semesterId" class="form-input"><option value="">Semua semester</option>@foreach($semesters as $s)<option value="{{$s->id}}">{{$s->tahunAjaran->nama}} · {{ucfirst($s->nama)}}</option>@endforeach</select><select wire:model.live="kelasId" class="form-input"><option value="">Semua kelas</option>@foreach($kelas as $k)<option value="{{$k->id}}">{{$k->nama}}</option>@endforeach</select>@unless(auth()->user()->hasRole(['guru','siswa']))<select wire:model.live="guruId" class="form-input"><option value="">Semua guru</option>@foreach($guru as $g)<option value="{{$g->id}}">{{$g->nama_lengkap}}</option>@endforeach</select>@endunless<select wire:model.live="hari" class="form-input"><option value="">Semua hari</option>@foreach(['senin','selasa','rabu','kamis','jumat','sabtu'] as $h)<option value="{{$h}}">{{ucfirst($h)}}</option>@endforeach</select><button type="button" wire:click="$set('hari','')" class="btn-secondary">Reset Hari</button></form>
<div class="table-shell"><div class="table-scroll"><table class="data-table"><thead><tr><th>Hari</th><th>Jam</th><th>Kelas</th><th>Mata Pelajaran</th><th>Guru</th>@can('jadwal.update')<th class="sticky right-0 bg-slate-50">Aksi</th>@endcan</tr></thead><tbody>@forelse($jadwal as $j)<tr><td class="font-semibold capitalize">{{$j->hari}}</td><td class="tabular-nums">{{substr($j->jamPelajaran->jam_mulai,0,5)}}–{{substr($j->jamPelajaran->jam_selesai,0,5)}}</td><td>{{$j->pengajaran->kelas->nama}}</td><td>{{$j->pengajaran->mataPelajaran->nama}}</td><td>{{$j->pengajaran->guru->nama_lengkap}}</td>@can('jadwal.update')<td class="sticky right-0 bg-white"><div class="flex gap-2"><button wire:click="edit({{$j->id}})" class="btn-secondary">Ubah</button><button wire:click="delete({{$j->id}})" wire:confirm="Hapus jadwal ini?" class="btn-secondary text-rose-700">Hapus</button></div></td>@endcan</tr>@empty<tr><td colspan="6" class="py-14 text-center text-slate-500">Belum ada jadwal pada filter ini.</td></tr>@endforelse</tbody></table></div></div>
@if($showForm)<div class="fixed inset-0 z-[80] grid place-items-center bg-slate-950/50 p-4"><form wire:submit="save" class="card w-full max-w-xl"><div class="border-b p-5"><h2 class="text-lg font-semibold">{{$editingId?'Ubah':'Tambah'}} Jadwal</h2></div><div class="space-y-5 p-5"><div><label class="form-label">Pengajaran <span>*</span></label><select wire:model="form.pengajaran_id" class="form-input"><option value="">Pilih pengajaran</option>@foreach($pengajaran as $p)<option value="{{$p->id}}">{{$p->kelas->nama}} · {{$p->mataPelajaran->nama}} · {{$p->guru->nama_lengkap}} ({{ucfirst($p->semester->nama)}})</option>@endforeach</select>@error('form.pengajaran_id')<p class="form-error">{{$message}}</p>@enderror</div><div class="grid gap-4 sm:grid-cols-2"><div><label class="form-label">Hari <span>*</span></label><select wire:model="form.hari" class="form-input">@foreach(['senin','selasa','rabu','kamis','jumat','sabtu'] as $h)<option value="{{$h}}">{{ucfirst($h)}}</option>@endforeach</select></div><div><label class="form-label">Jam <span>*</span></label><select wire:model="form.jam_pelajaran_id" class="form-input"><option value="">Pilih jam</option>@foreach($jam as $jp)<option value="{{$jp->id}}">{{$jp->nama}} · {{substr($jp->jam_mulai,0,5)}}–{{substr($jp->jam_selesai,0,5)}}</option>@endforeach</select></div></div>@error('jadwal')<p class="form-error rounded-xl bg-rose-50 p-3">{{$message}}</p>@enderror</div><div class="flex justify-end gap-3 border-t p-5"><button type="button" wire:click="$set('showForm',false)" class="btn-secondary">Batal</button><button class="btn-primary" wire:loading.attr="disabled">Simpan</button></div></form></div>@endif</div>
