<?php
use App\Livewire\Concerns\WithDataTable;
use App\Models\{Guru,JadwalPelajaran,JamPelajaran,Kelas,Pengajaran,Semester,TahunAjaran};
use App\Services\{PeriodeAktif,ValidasiJadwal};
use Illuminate\Validation\ValidationException;
use Livewire\Attributes\Url;
use Livewire\Component;

new class extends Component {
    use WithDataTable;
    #[Url] public string $hari=''; #[Url(as:'semester')] public string $semesterId=''; #[Url(as:'kelas')] public string $kelasId=''; #[Url(as:'guru')] public string $guruId='';
    public bool $showForm=false; public ?int $editingId=null; public array $form=['pengajaran_id'=>'','hari'=>'senin','jam_pelajaran_id'=>''];
    public string $formTahunAjaranId=''; public string $formSemesterId=''; public string $formKelasId='';
    public function mount():void{$this->semesterId=(string)($this->semesterId?:app(PeriodeAktif::class)->semester()?->id);$this->initializeDataTable();}
    public function updatedHari():void{$this->datasetChanged();}public function updatedSemesterId():void{$this->datasetChanged();}public function updatedKelasId():void{$this->datasetChanged();}public function updatedGuruId():void{$this->datasetChanged();}
    public function updatedFormTahunAjaranId():void{$this->formSemesterId='';$this->formKelasId='';$this->form['pengajaran_id']='';$this->resetValidation();}
    public function updatedFormSemesterId():void{$this->form['pengajaran_id']='';$this->resetValidation(['formSemesterId','form.pengajaran_id']);}
    public function updatedFormKelasId():void{$this->form['pengajaran_id']='';$this->resetValidation(['formKelasId','form.pengajaran_id']);}
    public function resetTableFilters():void{$this->hari='';$this->semesterId='';$this->kelasId='';$this->guruId='';}
    protected function tableSortableColumns():array{return ['hari','jam','kelas','mata_pelajaran','guru'];}
    protected function tableColumns():array{return [['id'=>'hari','label'=>'Hari','sortable'=>'hari'],['id'=>'jam','label'=>'Jam','sortable'=>'jam'],['id'=>'kelas','label'=>'Kelas','sortable'=>'kelas'],['id'=>'mata_pelajaran','label'=>'Mata Pelajaran','sortable'=>'mata_pelajaran'],['id'=>'guru','label'=>'Guru','sortable'=>'guru']];}
    public function openCreate():void{abort_unless(auth()->user()->can('jadwal.create'),403);$this->resetValidation();$this->editingId=null;$this->formTahunAjaranId='';$this->formSemesterId='';$this->formKelasId='';$this->form=['pengajaran_id'=>'','hari'=>'senin','jam_pelajaran_id'=>''];$this->showForm=true;}
    public function edit(int $id):void{abort_unless(auth()->user()->can('jadwal.update'),403);$this->resetValidation();$j=JadwalPelajaran::with('pengajaran.semester')->findOrFail($id);$this->editingId=$id;$this->form=$j->only(['pengajaran_id','hari','jam_pelajaran_id']);$this->formTahunAjaranId=(string)$j->pengajaran->semester->tahun_ajaran_id;$this->formSemesterId=(string)$j->pengajaran->semester_id;$this->formKelasId=(string)$j->pengajaran->kelas_id;$this->showForm=true;}
    public function save():void{abort_unless(auth()->user()->can($this->editingId?'jadwal.update':'jadwal.create'),403);$validated=$this->validate(['formTahunAjaranId'=>'required|integer|exists:tahun_ajaran,id','formSemesterId'=>'required|integer|exists:semester,id','formKelasId'=>'required|integer|exists:kelas,id','form.pengajaran_id'=>'required|exists:pengajaran,id','form.hari'=>'required|in:senin,selasa,rabu,kamis,jumat,sabtu','form.jam_pelajaran_id'=>'required|exists:jam_pelajaran,id'],['formTahunAjaranId.required'=>'Tahun ajaran wajib dipilih terlebih dahulu.','formSemesterId.required'=>'Semester wajib dipilih.','formKelasId.required'=>'Kelas wajib dipilih.']);$data=$validated['form'];if(!Semester::whereKey($this->formSemesterId)->where('tahun_ajaran_id',$this->formTahunAjaranId)->exists())throw ValidationException::withMessages(['formSemesterId'=>'Semester tidak sesuai dengan tahun ajaran yang dipilih.']);if(!Kelas::whereKey($this->formKelasId)->where('tahun_ajaran_id',$this->formTahunAjaranId)->exists())throw ValidationException::withMessages(['formKelasId'=>'Kelas tidak sesuai dengan tahun ajaran yang dipilih.']);$p=Pengajaran::query()->whereKey($data['pengajaran_id'])->where('semester_id',$this->formSemesterId)->where('kelas_id',$this->formKelasId)->first();if(!$p)throw ValidationException::withMessages(['form.pengajaran_id'=>'Pengajaran tidak sesuai dengan tahun ajaran, semester, dan kelas yang dipilih.']);app(ValidasiJadwal::class)->handle($p,$data['hari'],(int)$data['jam_pelajaran_id'],$this->editingId);JadwalPelajaran::updateOrCreate(['id'=>$this->editingId],$data);$this->showForm=false;session()->flash('success','Jadwal berhasil disimpan.');}
    public function delete(int $id):void{abort_unless(auth()->user()->can('jadwal.delete'),403);JadwalPelajaran::findOrFail($id)->delete();$this->clearSelection();$this->resetPage();$this->dispatch('notify',type:'success',message:'Jadwal berhasil dihapus.');}
    private function tableQuery(){ $u=auth()->user();$query=JadwalPelajaran::query()->select('jadwal_pelajaran.*')->join('pengajaran','pengajaran.id','=','jadwal_pelajaran.pengajaran_id')->join('jam_pelajaran','jam_pelajaran.id','=','jadwal_pelajaran.jam_pelajaran_id')->join('kelas','kelas.id','=','pengajaran.kelas_id')->join('mata_pelajaran','mata_pelajaran.id','=','pengajaran.mata_pelajaran_id')->join('guru','guru.id','=','pengajaran.guru_id')->with(['pengajaran.semester.tahunAjaran','pengajaran.kelas','pengajaran.guru','pengajaran.mataPelajaran','jamPelajaran'])->when($this->search,fn($q)=>$q->where(fn($x)=>$x->where('kelas.nama','like','%'.$this->search.'%')->orWhere('mata_pelajaran.nama','like','%'.$this->search.'%')->orWhere('guru.nama_lengkap','like','%'.$this->search.'%')))->when($this->semesterId,fn($q)=>$q->where('pengajaran.semester_id',$this->semesterId))->when($this->kelasId,fn($q)=>$q->where('pengajaran.kelas_id',$this->kelasId))->when($this->guruId,fn($q)=>$q->where('pengajaran.guru_id',$this->guruId))->when($this->hari,fn($q)=>$q->where('jadwal_pelajaran.hari',$this->hari));if($u->hasRole('guru'))$query->where('pengajaran.guru_id',$u->guru?->id);if($u->hasRole('siswa')){$kid=$u->siswa?->penempatanKelas()->where('status','aktif')->value('kelas_id');$query->where('pengajaran.kelas_id',$kid);}return $query;}
    private function applyTableSort($query){$map=['hari'=>'jadwal_pelajaran.hari','jam'=>'jam_pelajaran.urutan','kelas'=>'kelas.nama','mata_pelajaran'=>'mata_pelajaran.nama','guru'=>'guru.nama_lengkap'];if($this->sort!=='')return $query->orderBy($map[$this->sort],$this->direction);return $query->orderByRaw("CASE jadwal_pelajaran.hari WHEN 'senin' THEN 1 WHEN 'selasa' THEN 2 WHEN 'rabu' THEN 3 WHEN 'kamis' THEN 4 WHEN 'jumat' THEN 5 WHEN 'sabtu' THEN 6 ELSE 7 END")->orderBy('jam_pelajaran.urutan');}
    public function bulkDelete():void{abort_unless(auth()->user()->can('jadwal.delete'),403);$selected=$this->applySelection($this->tableQuery())->select('jadwal_pelajaran.id');$count=JadwalPelajaran::whereIn('id',$selected)->delete();$this->clearSelection();$this->resetPage();$this->dispatch('notify',type:'success',message:$count.' jadwal berhasil dihapus.');}
    public function with():array{$error=null;try{$query=$this->tableQuery();$total=(clone $query)->count();$jadwal=$this->applyTableSort($query)->paginate($this->perPage);}catch(\Throwable $exception){report($exception);$error='Terjadi kesalahan saat mengambil jadwal.';$total=0;$jadwal=JadwalPelajaran::query()->whereRaw('1=0')->paginate($this->perPage);}$formSemesters=$this->showForm&&$this->formTahunAjaranId?Semester::where('tahun_ajaran_id',$this->formTahunAjaranId)->orderByDesc('tanggal_mulai')->get():collect();$formClasses=$this->showForm&&$this->formTahunAjaranId?Kelas::where('tahun_ajaran_id',$this->formTahunAjaranId)->where(function($q){$q->where('status','aktif');if($this->formKelasId)$q->orWhere('kelas.id',$this->formKelasId);})->orderBy('tingkat')->orderBy('nama')->get():collect();$formTeachings=$this->showForm&&$this->formSemesterId&&$this->formKelasId?Pengajaran::with(['guru','mataPelajaran'])->where('semester_id',$this->formSemesterId)->where('kelas_id',$this->formKelasId)->where(function($q){$q->where('status','aktif');if($this->form['pengajaran_id']??null)$q->orWhere('pengajaran.id',$this->form['pengajaran_id']);})->orderBy('mata_pelajaran_id')->get():collect();return ['jadwal'=>$jadwal,'datasetTotal'=>$total,'tableColumns'=>$this->tableColumns(),'visibleColumnIds'=>$this->validatedVisibleColumns(),'tableError'=>$error,'semesters'=>Semester::with('tahunAjaran')->get(),'kelas'=>Kelas::orderBy('nama')->get(),'guru'=>Guru::orderBy('nama_lengkap')->get(),'tahunAjaran'=>TahunAjaran::orderByDesc('nama')->get(),'formSemesters'=>$formSemesters,'formClasses'=>$formClasses,'formTeachings'=>$formTeachings,'jam'=>JamPelajaran::where('jenis','pelajaran')->where('status','aktif')->orderBy('urutan')->get()];}
}; ?>
<div><div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-sky-700">Akademik</p><h1 class="page-title">Jadwal Pelajaran</h1><p class="page-subtitle">Jadwal mingguan sesuai kelas dan hak akses pengguna.</p></div>@can('jadwal.create')<button wire:click="openCreate" class="btn-primary">Tambah Jadwal</button>@endcan</div>
<div class="mb-4 grid gap-3 lg:grid-cols-[minmax(18rem,1fr)_auto]"><div class="card p-4"><label class="form-label" for="jadwal-search">Pencarian Utama</label><input id="jadwal-search" type="search" wire:model.live.debounce.400ms="search" class="form-input" placeholder="Cari kelas, mata pelajaran, atau guru..."></div><div class="card flex items-end gap-3 p-4"><button type="button" wire:click="resetTableState" class="btn-secondary">Reset Filter</button><x-data-table.column-toggle :columns="$tableColumns" :visible="$visibleColumnIds" /></div></div>
<div class="filters card mb-5 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-4"><x-searchable-select model="semesterId" :value="$semesterId" :options="$semesters->mapWithKeys(fn($s)=>[$s->id=>$s->tahunAjaran->nama.' · '.ucfirst($s->nama)])->all()" placeholder="Semua semester" search-placeholder="Cari semester..." /><x-searchable-select model="kelasId" :value="$kelasId" :options="$kelas->pluck('nama','id')->all()" placeholder="Semua kelas" search-placeholder="Cari kelas..." />@unless(auth()->user()->hasRole(['guru','siswa']))<x-searchable-select model="guruId" :value="$guruId" :options="$guru->pluck('nama_lengkap','id')->all()" placeholder="Semua guru" search-placeholder="Cari guru..." />@endunless<x-searchable-select model="hari" :value="$hari" :options="collect(['senin','selasa','rabu','kamis','jumat','sabtu'])->mapWithKeys(fn($h)=>[$h=>ucfirst($h)])->all()" placeholder="Semua hari" search-placeholder="Cari hari..." /></div>
<x-data-table.bulk-toolbar :count="$this->selectedCount($datasetTotal)">@can('jadwal.delete')<button type="button" wire:click="bulkDelete" wire:confirm="Hapus {{ $this->selectedCount($datasetTotal) }} jadwal terpilih?" class="btn-danger">Hapus Terpilih</button>@endcan</x-data-table.bulk-toolbar>
<div class="table-shell"><div class="table-scroll"><table class="data-table"><thead><tr><th class="table-select-cell sticky left-0 z-20 w-14"><input type="checkbox" class="size-4 rounded border-slate-300 text-sky-600" wire:click="toggleSelectAllDataset" @checked($datasetTotal>0&&$this->selectedCount($datasetTotal)===$datasetTotal) x-data x-effect="$el.indeterminate={{ $this->selectedCount($datasetTotal)>0&&$this->selectedCount($datasetTotal)<$datasetTotal?'true':'false' }}" aria-label="Pilih seluruh jadwal hasil filter"></th>@foreach($tableColumns as $column)@continue(!in_array($column['id'],$visibleColumnIds,true))<th><button type="button" wire:click="sortBy('{{ $column['sortable'] }}')" class="inline-flex min-h-11 items-center gap-1" aria-label="Urutkan {{ $column['label'] }}">{{ $column['label'] }} <span aria-hidden="true">{{ $sort===$column['sortable']?($direction==='asc'?'↑':'↓'):'↕' }}</span></button></th>@endforeach<th class="table-action-cell sticky right-0 z-20">Aksi</th></tr></thead><tbody>@foreach($jadwal as $j)@php $selected=$this->isRowSelected($j->id);@endphp<tr class="{{ $selected?'is-selected':'' }}" wire:key="jadwal-row-{{$j->id}}" wire:loading.remove><td class="table-select-cell sticky left-0 z-10"><input type="checkbox" class="size-4 rounded border-slate-300 text-sky-600" @checked($selected) wire:click="toggleRowSelection({{$j->id}})" aria-label="Pilih jadwal {{$j->pengajaran->mataPelajaran->nama}}"></td>@foreach($tableColumns as $column)@continue(!in_array($column['id'],$visibleColumnIds,true))<td>@switch($column['id'])@case('hari')<span class="font-semibold capitalize">{{$j->hari}}</span>@break @case('jam')<span class="tabular-nums">{{substr($j->jamPelajaran->jam_mulai,0,5)}}–{{substr($j->jamPelajaran->jam_selesai,0,5)}}</span>@break @case('kelas'){{$j->pengajaran->kelas->nama}}@break @case('mata_pelajaran'){{$j->pengajaran->mataPelajaran->nama}}@break @case('guru'){{$j->pengajaran->guru->nama_lengkap}}@break @endswitch</td>@endforeach<td class="table-action-cell sticky right-0 z-10"><div class="flex gap-2">@can('jadwal.update')<button wire:click="edit({{$j->id}})" class="btn-secondary">Ubah</button>@endcan @can('jadwal.delete')<button wire:click="delete({{$j->id}})" wire:confirm="Hapus jadwal ini?" class="btn-secondary text-rose-700">Hapus</button>@endcan @cannot('jadwal.update')<span class="text-slate-400">—</span>@endcannot</div></td></tr>@endforeach<x-data-table.states :columns="count($visibleColumnIds)+2" :empty="$jadwal->isEmpty()" :filtered="filled($search)||filled($semesterId)||filled($kelasId)||filled($guruId)||filled($hari)" :error="$tableError" /></tbody></table></div><x-data-table.pagination :paginator="$jadwal" :per-page="$perPage" /></div>
@if($showForm)<div class="fixed inset-0 z-[80] grid place-items-center overflow-y-auto bg-slate-950/50 p-4"><form wire:submit="save" class="card w-full max-w-2xl"><div class="flex items-center justify-between border-b p-5"><div><h2 class="text-lg font-semibold">{{$editingId?'Ubah':'Tambah'}} Jadwal</h2><p class="mt-1 text-sm text-slate-500">Pilih periode dan kelas terlebih dahulu agar pengajaran yang tampil sesuai.</p></div><button type="button" wire:click="$set('showForm',false)" class="grid size-11 place-items-center rounded-lg hover:bg-slate-100" aria-label="Tutup">&times;</button></div><div class="grid max-h-[70vh] gap-5 overflow-y-auto p-5 sm:grid-cols-2">
<div><label class="form-label">Tahun Ajaran <span>*</span></label><x-searchable-select model="formTahunAjaranId" :value="$formTahunAjaranId" :options="$tahunAjaran->pluck('nama','id')->all()" placeholder="Pilih tahun ajaran dahulu..." search-placeholder="Cari tahun ajaran..." />@error('formTahunAjaranId')<p class="form-error" role="alert">{{$message}}</p>@enderror</div>
<div><label class="form-label">Semester <span>*</span></label>@if($formTahunAjaranId)<x-searchable-select model="formSemesterId" :value="$formSemesterId" :options="$formSemesters->mapWithKeys(fn($semester)=>[$semester->id=>ucfirst($semester->nama)])->all()" placeholder="Pilih semester..." search-placeholder="Cari semester..." />@else<button type="button" disabled class="form-input cursor-not-allowed text-left text-slate-400">Pilih tahun ajaran terlebih dahulu</button>@endif @error('formSemesterId')<p class="form-error" role="alert">{{$message}}</p>@enderror</div>
<div><label class="form-label">Kelas <span>*</span></label>@if($formTahunAjaranId)<x-searchable-select model="formKelasId" :value="$formKelasId" :options="$formClasses->pluck('nama','id')->all()" placeholder="Pilih kelas..." search-placeholder="Cari kelas..." />@else<button type="button" disabled class="form-input cursor-not-allowed text-left text-slate-400">Pilih tahun ajaran terlebih dahulu</button>@endif @error('formKelasId')<p class="form-error" role="alert">{{$message}}</p>@enderror</div>
<div><label class="form-label">Pengajaran <span>*</span></label>@if($formSemesterId&&$formKelasId)<x-searchable-select model="form.pengajaran_id" :value="$form['pengajaran_id']??''" :options="$formTeachings->mapWithKeys(fn($p)=>[$p->id=>$p->mataPelajaran->nama.' · '.$p->guru->nama_lengkap])->all()" placeholder="Pilih pengajaran..." search-placeholder="Cari mata pelajaran atau guru..." />@else<button type="button" disabled class="form-input cursor-not-allowed text-left text-slate-400">Pilih semester dan kelas terlebih dahulu</button>@endif @error('form.pengajaran_id')<p class="form-error" role="alert">{{$message}}</p>@enderror</div>
<div><label class="form-label">Hari <span>*</span></label><select wire:model="form.hari" class="form-input">@foreach(['senin','selasa','rabu','kamis','jumat','sabtu'] as $h)<option value="{{$h}}">{{ucfirst($h)}}</option>@endforeach</select>@error('form.hari')<p class="form-error" role="alert">{{$message}}</p>@enderror</div>
<div><label class="form-label">Jam <span>*</span></label><select wire:model="form.jam_pelajaran_id" class="form-input"><option value="">Pilih jam</option>@foreach($jam as $jp)<option value="{{$jp->id}}">{{$jp->nama}} · {{substr($jp->jam_mulai,0,5)}}–{{substr($jp->jam_selesai,0,5)}}</option>@endforeach</select>@error('form.jam_pelajaran_id')<p class="form-error" role="alert">{{$message}}</p>@enderror</div>
@error('jadwal')<p class="form-error rounded-xl bg-rose-50 p-3 sm:col-span-2">{{$message}}</p>@enderror</div><div class="flex justify-end gap-3 border-t p-5"><button type="button" wire:click="$set('showForm',false)" class="btn-secondary">Batal</button><button class="btn-primary" wire:loading.attr="disabled"><span wire:loading.remove wire:target="save">Simpan</span><span wire:loading wire:target="save">Menyimpan...</span></button></div></form></div>@endif</div>
