<?php
use App\Models\{NilaiTugas,Pengajaran}; use App\Services\{PenyimpananNilaiMassal,PeriodeAktif}; use Livewire\Attributes\Url; use Livewire\Component;
new class extends Component {
    #[Url] public string $pengajaranId=''; #[Url] public int $bulan=8; public array $nilai=[];
    public function mount():void{$this->bulan=(int)(request('bulan')?:now()->month);$this->loadNilai();}
    public function updatedPengajaranId():void{$this->loadNilai();} public function updatedBulan():void{$this->loadNilai();}
    public function loadNilai():void{$this->nilai=[];if(!$this->pengajaranId)return;$p=$this->authorizedTeaching();$ids=$p->kelas->siswaKelas()->where('status','aktif')->pluck('siswa_id');foreach($ids as $id)foreach(range(1,4)as$w)$this->nilai[$id][$w]='';foreach(NilaiTugas::where('pengajaran_id',$p->id)->where('bulan',$this->bulan)->get() as $n)$this->nilai[$n->siswa_id][$n->minggu]=$n->nilai===null?'':(float)$n->nilai;}
    private function authorizedTeaching():Pengajaran{$p=Pengajaran::with('kelas.siswaKelas')->findOrFail($this->pengajaranId);if(auth()->user()->hasRole('guru'))abort_unless($p->guru_id===auth()->user()->guru?->id,403);if(auth()->user()->hasRole('siswa'))abort(403);return $p;}
    public function save():void{abort_unless(auth()->user()->can('nilai.create'),403);$p=$this->authorizedTeaching();app(PenyimpananNilaiMassal::class)->handle(auth()->user(),$p,$this->bulan,$this->nilai);session()->flash('success','Nilai seluruh siswa berhasil disimpan.');}
    public function average(array $weeks):string{$v=collect($weeks)->filter(fn($x)=>$x!==''&&$x!==null)->map(fn($x)=>(float)$x);return $v->isEmpty()?'-':number_format($v->avg(),2);}
    public function with():array{$u=auth()->user();$teachings=Pengajaran::with(['semester.tahunAjaran','kelas','mataPelajaran','guru'])->where('status','aktif')->when($u->hasRole('guru'),fn($q)=>$q->where('guru_id',$u->guru?->id))->orderBy('kelas_id')->get();$students=collect();if($this->pengajaranId){$p=$teachings->firstWhere('id',(int)$this->pengajaranId)??($u->hasAnyRole(['admin','kepala_sekolah'])?Pengajaran::with(['kelas.siswa','mataPelajaran','guru','semester.tahunAjaran'])->find($this->pengajaranId):null);if($p)$students=$p->kelas->siswa()->wherePivot('status','aktif')->orderBy('nama_lengkap')->get();}
        $studentRows=collect();if($u->hasRole('siswa')){$studentRows=NilaiTugas::with(['pengajaran.mataPelajaran','pengajaran.guru','pengajaran.semester.tahunAjaran'])->where('siswa_id',$u->siswa?->id)->where('bulan',$this->bulan)->get()->groupBy('pengajaran_id');}
        return compact('teachings','students','studentRows');}
}; ?>
<div><div class="mb-6"><p class="text-sm font-semibold text-sky-700">Akademik</p><h1 class="page-title">{{auth()->user()->hasRole('siswa')?'Nilai Saya':'Nilai Siswa'}}</h1><p class="page-subtitle">Nilai tugas Minggu 1–4; kolom kosong berarti belum dinilai, bukan nol.</p></div>
@if(auth()->user()->hasRole('siswa'))<div class="card mb-5 max-w-xs p-4"><label class="form-label">Bulan</label><select wire:model.live="bulan" class="form-input">@foreach(range(1,12) as $m)<option value="{{$m}}">{{\Carbon\Carbon::create()->month($m)->translatedFormat('F')}}</option>@endforeach</select></div><div class="table-shell"><div class="table-scroll"><table class="data-table"><thead><tr><th>Mata Pelajaran</th><th>Guru</th><th>M1</th><th>M2</th><th>M3</th><th>M4</th><th>Rata-rata</th></tr></thead><tbody>@forelse($studentRows as $rows)@php $first=$rows->first();$weeks=collect(range(1,4))->mapWithKeys(fn($w)=>[$w=>$rows->firstWhere('minggu',$w)?->nilai]); @endphp<tr><td class="font-medium">{{$first->pengajaran->mataPelajaran->nama}}</td><td>{{$first->pengajaran->guru->nama_lengkap}}</td>@foreach(range(1,4) as $w)<td>{{$weeks[$w]===null?'-':number_format((float)$weeks[$w],0)}}</td>@endforeach<td class="font-semibold">{{$this->average($weeks->all())}}</td></tr>@empty<tr><td colspan="7" class="py-14 text-center text-slate-500">Belum ada nilai pada periode ini.</td></tr>@endforelse</tbody></table></div></div>
@else<form wire:submit="save"><div class="card mb-5 grid gap-4 p-4 lg:grid-cols-[1fr_14rem_auto]"><div><label class="form-label">Kelas · Mata Pelajaran · Guru</label><select wire:model.live="pengajaranId" class="form-input"><option value="">Pilih pengajaran</option>@foreach($teachings as $p)<option value="{{$p->id}}">{{$p->kelas->nama}} · {{$p->mataPelajaran->nama}} · {{$p->guru->nama_lengkap}} · {{$p->semester->tahunAjaran->nama}}</option>@endforeach</select></div><div><label class="form-label">Bulan</label><select wire:model.live="bulan" class="form-input">@foreach(range(1,12) as $m)<option value="{{$m}}">{{\Carbon\Carbon::create()->month($m)->translatedFormat('F')}}</option>@endforeach</select></div>@can('nilai.create')<div class="self-end"><button class="btn-primary w-full" wire:loading.attr="disabled" @disabled(!$pengajaranId)><span wire:loading.remove>Simpan Nilai</span><span wire:loading>Menyimpan...</span></button></div>@endcan</div>
<div class="table-shell"><div class="table-scroll"><table class="data-table min-w-[850px]"><thead><tr><th class="sticky left-0 z-20 min-w-52 bg-slate-50">Nama Siswa</th>@foreach(range(1,4) as $w)<th class="w-32">Minggu {{$w}}</th>@endforeach<th>Rata-rata</th></tr></thead><tbody>@forelse($students as $s)<tr><td class="sticky left-0 bg-white font-medium">{{$s->nama_lengkap}}</td>@foreach(range(1,4) as $w)<td>@can('nilai.create')<input type="number" min="0" max="100" step=".01" inputmode="decimal" wire:model.live.debounce.500ms="nilai.{{$s->id}}.{{$w}}" class="form-input w-24 tabular-nums" aria-label="Nilai {{$s->nama_lengkap}} minggu {{$w}}">@else{{data_get($nilai,$s->id.'.'.$w)===''?'-':data_get($nilai,$s->id.'.'.$w)}}@endcan @error('nilai.'.$s->id.'.'.$w)<p class="form-error">0–100</p>@enderror</td>@endforeach<td class="font-semibold tabular-nums">{{$this->average($nilai[$s->id]??[])}}</td></tr>@empty<tr><td colspan="6" class="py-14 text-center text-slate-500">{{$pengajaranId?'Belum ada siswa aktif pada kelas ini.':'Pilih pengajaran untuk menampilkan seluruh siswa.'}}</td></tr>@endforelse</tbody></table></div></div></form>@endif</div>
